### Watermark - POST
POST http://localhost:3000/watermark
Content-Type: multipart/form-data; boundary=boundary123

--boundary123
Content-Disposition: form-data; name="pdf"; filename="sample.pdf"
Content-Type: application/pdf

< ./sample.pdf
--boundary123
Content-Disposition: form-data; name="email"

jonatanpotrikus@gmail.com
--boundary123
Content-Disposition: form-data; name="nome"

Jonatan Potrikus
--boundary123--


### Watermark - GET - Buscar por URL
GET http://localhost:3000/download?email=jonatan@gmail.com&name=JonatanPotrikus&arquivo=https://ontheline.trincoll.edu/images/bookdown/sample-local-pdf.pdf

Content-Type: application/json


### Watermark - GET - Buscar por URL Com location
GET http://localhost:3000/download?email=jonatan@gmail.com&name=JonatanPotrikus&arquivo=https%3A%2F%2Fbravi.instructure.com%2Fcourses%2F227%2Ffiles%2F2034%2Fdownload%3Fdownload_frd%3D1%26verifier%3DbSDEgXHDxaCs7aD9Va6IZvGSotfq2rxvgQ6lHzMt

Content-Type: application/json