### Watermark - POST
POST http://localhost:3000/watermark
Content-Type: multipart/form-data; boundary=boundary123

--boundary123
Content-Disposition: form-data; name="pdf"; filename="sample.pdf"
Content-Type: application/pdf

< ./sample.pdf
--boundary123
Content-Disposition: form-data; name="email"

jonatanpotrikus@gmail.com
--boundary123
Content-Disposition: form-data; name="nome"

Jonatan Potrikus
--boundary123--


### Watermark - GET - Buscar por URL
GET http://localhost:3000/download?email=jonatan@gmail.com&name=JonatanPotrikus&arquivo=https://ontheline.trincoll.edu/images/bookdown/sample-local-pdf.pdf
Content-Type: application/json